[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "aetheris-file-manager-by-miguel"
version = "0.1.0"
description = "Aetheris File Manager by Miguel"
authors = [{ name = "Miguel" }]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "PyQt6>=6.4.0"
]

[project.scripts]
aetheris-file-manager-by-miguel = "aetheris_fm.main:main"
